global.chalk = require('chalk')
global.app = require('express')()
global.async = require('async')
global.Sequelize = require('sequelize')
global.utils = require('./utils')
global._ = require('lodash')
